name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }} 
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CYPRESS_CLIENT_ID: ${{ secrets.CYPRESS_CLIENT_ID }}
      CYPRESS_DEK: ${{ secrets.CYPRESS_DEK }}
      CYPRESS_PUBLIC_KEY: ${{ secrets.CYPRESS_PUBLIC_KEY }}
      CYPRESS_SESSIONTOKEN: ${{ secrets.CYPRESS_SESSIONTOKEN }}
      CYPRESS_TEST_TOKEN_PAIR: ${{ secrets.CYPRESS_SESSIONTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PNPM Setup
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Get Deps
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Rename Cypress Config 
        run: mv cypress.config.ts.example cypress.config.ts
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1
        with:
          build: pnpm run build
          start: pnpm run preview
